#!/bin/sh

dir=`pwd`

[ "$dir" == "$HOME" ] && echo "Cannot run script in home directory." && exit
[ ! -e .Xresources ] && echo "Error: .Xresources not found." && exit
[ ! -e .emacs ] && echo "Error: .emacs not found." && exit

rm -f ~/.Xresources ~/.emacs
ln -s $dir/.Xresources ~
ln -s $dir/.emacs ~

